[[regexes]]
  name = "example regex entry"
  description = "example regex entry description"
  re = "(?P<msg>.*)"

[options]
  show_matches = true
  show_misses = false
  show_all_matches = false
  match_sample_size = 0
  show_multiple_matches = false

[plugin]
  id = 84030
  name = "default-plugin-name"
  version = ""
  description = ""
  log_file = "/var/log/syslog"
  website = "http://www.example.org"
  log_format = "-"

[vendor]
  name = "Default Vendor"
  model = "Default Vendor Model"
  version = "-"
  per_asset = false

[author]
  name = "Default Author"
  email = "default@example.org"
